services:
  db:
    image: mysql:8.4
    container_name: rotadocaso-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: rotadocaso
      MYSQL_USER: rotadocaso
      MYSQL_PASSWORD: rotadocaso_dev
      MYSQL_ROOT_PASSWORD: altere_a_senha_root_local
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
